# Final notes

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx

In [2]:
%config InlineBackend.figure_format = "retina"

## Question 1

In [44]:
edges = np.array([
    [1, 2],
    [1, 4],
    [1, 7],
    [2, 3],
    [2, 6],
    [2, 7],
    [3, 4],
    [3, 5],
    [3, 6],
    [4, 5],
    [5, 6],
    [5, 7],
    [6, 7]
]) - 1

In [67]:
nodelist = np.arange(n_nodes)
G = nx.from_edgelist(edges)

In [68]:
# Computing adjacency matrix
A = nx.adjacency_matrix(G, nodelist).todense()
A

matrix([[0, 1, 0, 1, 0, 0, 1],
        [1, 0, 1, 0, 0, 1, 1],
        [0, 1, 0, 1, 1, 1, 0],
        [1, 0, 1, 0, 1, 0, 0],
        [0, 0, 1, 1, 0, 1, 1],
        [0, 1, 1, 0, 1, 0, 1],
        [1, 1, 0, 0, 1, 1, 0]])

In [69]:
# Computing incidence matrix
B = nx.incidence_matrix(G, nodelist, edges).todense()
B

matrix([[1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1.],
        [0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1.]])

Computing average node degree

In [84]:
degrees = np.array(A.sum(axis=1)).ravel()
degrees

array([3, 4, 4, 3, 4, 4, 4])

In [85]:
degrees.mean()

3.7142857142857144

In [86]:
# 2 out of 7 nodes have degree 3 + 5 out of 7 have degree 4
3 * 2/7 + 4 * 5/7

3.7142857142857144

Evaluating average clustering coefficient

First we compare individual clustering coefficents

In [90]:
nx.clustering(G)

{0: 0.3333333333333333,
 1: 0.5,
 3: 0.3333333333333333,
 6: 0.5,
 2: 0.5,
 5: 0.6666666666666666,
 4: 0.5}

In [98]:
A ** 3

matrix([[ 2,  8,  5,  7,  5,  6,  8],
        [ 8,  6, 11,  5,  7, 10, 10],
        [ 5, 11,  6,  8, 10, 10,  7],
        [ 7,  5,  8,  2,  8,  6,  5],
        [ 5,  7, 10,  8,  6, 10, 11],
        [ 6, 10, 10,  6, 10,  8, 10],
        [ 8, 10,  7,  5, 11, 10,  6]])

In [92]:
clustering_coefs = np.diag() / (degrees * (degrees - 1))
clustering_coefs

array([0.33333333, 0.5       , 0.5       , 0.33333333, 0.5       ,
       0.66666667, 0.5       ])

Next, we compute the average of the clustering coefficients

In [94]:
clustering_coefs.mean()

0.47619047619047616

In [87]:
nx.average_clustering(G)

0.47619047619047616

Finding matrix of distances

In [114]:
D = nx.floyd_warshall_numpy(G, nodelist)
D

array([[0., 1., 2., 1., 2., 2., 1.],
       [1., 0., 1., 2., 2., 1., 1.],
       [2., 1., 0., 1., 1., 1., 2.],
       [1., 2., 1., 0., 1., 2., 2.],
       [2., 2., 1., 1., 0., 1., 1.],
       [2., 1., 1., 2., 1., 0., 1.],
       [1., 1., 2., 2., 1., 1., 0.]])

In [117]:
D.max(axis=1).min()

2.0

In [111]:
nx.diameter(G)

2

In [142]:
# Distance matrix
D

array([[0., 1., 2., 1., 2., 2., 1.],
       [1., 0., 1., 2., 2., 1., 1.],
       [2., 1., 0., 1., 1., 1., 2.],
       [1., 2., 1., 0., 1., 2., 2.],
       [2., 2., 1., 1., 0., 1., 1.],
       [2., 1., 1., 2., 1., 0., 1.],
       [1., 1., 2., 2., 1., 1., 0.]])

In [133]:
nx.average_shortest_path_length(G)

1.380952380952381

In [143]:
D.sum() / (6 * 7)

1.380952380952381

Compute node closeness centrality

In [147]:
6 / D.sum(axis=1)

array([0.66666667, 0.75      , 0.75      , 0.66666667, 0.75      ,
       0.75      , 0.75      ])

In [144]:
nx.centrality.closeness_centrality(G)

{0: 0.6666666666666666,
 1: 0.75,
 3: 0.6666666666666666,
 6: 0.75,
 2: 0.75,
 5: 0.75,
 4: 0.75}

Compute betweeness centrality

In [155]:
nx.centrality.betweenness_centrality(G, normalized=False)

{0: 1.0,
 1: 1.3333333333333333,
 3: 1.0,
 6: 1.3333333333333333,
 2: 1.3333333333333333,
 5: 0.6666666666666666,
 4: 1.3333333333333333}

In [159]:
nx.centrality.betweenness_centrality(G, normalized=True)

{0: 0.06666666666666667,
 1: 0.08888888888888888,
 3: 0.06666666666666667,
 6: 0.08888888888888888,
 2: 0.08888888888888888,
 5: 0.04444444444444444,
 4: 0.08888888888888888}

In [161]:
2 / (6 * 5)

0.06666666666666667

In [150]:
4 / 9

0.4444444444444444

### Part b

In [162]:
Gp = np.array([
    [0, 1, 0, 0, 1, 0, 0],
    [0, 0, 1, 0, 1, 0, 0],
    [0, 0, 0, 1, 1, 0, 0],
    [1, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 1],
    [0, 0, 0, 0, 1, 1, 0]
])

In [165]:
np.linalg.eigvals(Gp).real

array([-1.00000000e+00+0.j,  8.32667268e-17+1.j,  8.32667268e-17-1.j,
        1.00000000e+00+0.j,  1.00000000e+00+0.j, -1.00000000e+00+0.j,
        0.00000000e+00+0.j])

In [178]:
edges_p = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 1],
    [1, 5],
    [2, 5],
    [3, 5],
    [4, 5],
    [6, 5],
    [7, 5],
    [6, 7],
    [7, 6]
]) - 1

In [179]:
Gp = nx.from_edgelist(edges_p, create_using=nx.DiGraph)
Ap = nx.adjacency_matrix(Gp).todense()
Ap

matrix([[0, 1, 0, 0, 1, 0, 0],
        [0, 0, 1, 0, 1, 0, 0],
        [0, 0, 0, 1, 1, 0, 0],
        [1, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 1],
        [0, 0, 0, 0, 1, 1, 0]])

# Q2

In [192]:
Gc = nx.configuration_model([2,2,1,1])
Gc.edges

MultiEdgeView([(0, 1, 0), (0, 1, 1), (2, 3, 0)])

In [189]:
Gc.degree()

MultiDegreeView({0: 2, 1: 2, 2: 1, 3: 1})

In [190]:
Gc.graph

{}